on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  run-test:
    runs-on: ubuntu-22.04
    environment:
      name: ${{ inputs.environment }}
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore composer cache (if available)
        id: composer-vendor-restore
        uses: actions/cache/restore@v3
        with:
          path: vendor/
          key: ${{ runner.os }}-composer-vendor-${{ hashFiles('composer.lock') }}

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi \
          --no-interaction --no-scripts --no-progress

      - name: Set env file
        run: |
          echo $BASE_64_SECRET | base64 -d > .env
          chmod 600 .env
        env:
          BASE_64_SECRET: ${{ secrets.ENV_FILE_BASE64 }}

      - name: Generate key
        run: php artisan key:generate

      - name: Generate test db
        run: |
          touch database/database.sqlite
          chmod 777 database/database.sqlite

      - name: Run migrate
        run: |
          php artisan migrate --force --env=testing

      - name: Run tests
        run: php artisan test

